update workflow

diff --git a/.github/workflows/gcp_monitor.yml b/.github/workflows/gcp_monitor.yml
--- a/.github/workflows/gcp_monitor.yml
+++ b/.github/workflows/gcp_monitor.yml
@@ -32,6 +32,7 @@ jobs:
 
     env:
       BUNDLE_GEMFILE: ${{ github.workspace }}/workflows_helper/gcp_monitor/Gemfile
+      TZ: "Asia/Tokyo"
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -43,7 +44,7 @@ jobs:
           credentials_json: '${{ secrets[matrix.credentials] }}'
 
       - name: 'Set up Cloud SDK'
-        uses: 'google-github-actions/setup-gcloud@v1.1.1'
+        uses: 'google-github-actions/setup-gcloud@v1'
 
       # Runs a single command using the runners shell
       - name: Get the date
@@ -55,18 +56,24 @@ jobs:
         run: |
           echo "past_date=$(TZ=Asia/Tokyo date -d '1 day ago' '+%Y-%m-%d')" >> $GITHUB_OUTPUT
           echo "current_date=$(TZ=Asia/Tokyo date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
+          date
+          TZ=Asia/Tokyo date
         shell: bash
       - name: search for all iam policies
         id: get_current_iam_policies
         run: |
-          gcloud asset search-all-iam-policies --scope=projects/${{ matrix.environment }} --format=json | jq '.' > iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.current_date }}.json
+          gcloud asset search-all-iam-policies --scope=projects/${{ matrix.environment }} --format=json > iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.current_date }}.json
           gsutil cp iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.current_date }}.json gs://cloud-asset-inventory-${{ matrix.environment }}
           echo "file_path=iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.current_date }}.json" >> $GITHUB_OUTPUT
       # Runs a set of commands using the runners shell
       # https://stackoverflow.com/a/74232400
       # https://github.com/github/docs/issues/21529
       - name: get old iam policies file
-        run: gsutil cp gs://cloud-asset-inventory-${{ matrix.environment }}/iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.past_date }}.json .
+        run: |
+          gsutil cp gs://cloud-asset-inventory-${{ matrix.environment }}/iam-policies-${{ matrix.environment }}-${{ steps.get_date.outputs.past_date }}.json . || (echo "Error downloading file from GCS." && exit 1)
+          date
+        env:
+          TZ: "Asia/Tokyo"
       - name: search for all gcp resources
         id: get_resources_diff
         run: |
